### ISSUE TITLE
Cannot encode type as TOML: string

### ISSUE THREAD

**Issue by anakinsleftleg** [g-s-k/matlab-toml#24]
```matlab
>> toml.encode(struct("key", "value"))
Error using repr
Cannot encode type as TOML: string
Error in repr (line 87)
        current_item_repr = repr(vals{indx}, new_parent);
Error in toml.encode (line 20)
      toml_str = repr(m_strct); 
```

Came across this today. Also generally displeased about shoving everything into a containers.Map but that ship has probably sailed.

**Comment by g-s-k** [comment]
Hi, sorry that I missed the string type. I have not had a MATLAB license for about 5 years, and Octave does not have a separate string type. I have uploaded a solution that I _think_ will work in #25, but I cannot test it. I would appreciate if you don't mind giving it a try.

As far as Map vs. struct goes, it is not possible to comply with the TOML specification with structs because of the rules for valid struct keys. The `map_to_struct` utility function provided with this library can be used after loading data with `decode`, if struct is a more useful data type to you.

**Comment by anakinsleftleg** [comment]
Yea, no more error.

```matlab
K>> toml.encode(struct("key", "value"))
ans = 
    "key = "value = "
     "
```
