### ISSUE TITLE
Values of [ [ 1 , 2 ] , [ 3 , 4 ] ] should return as 2x2 array, currently returns 1x4 vector

### ISSUE THREAD

**Issue by ghost** [g-s-k/matlab-toml#8]
Just as numpy uses nested brackets to signify different dimensions, so too should this TOML parser.

Currently
```
key = [ [ 1 , 2 ] , [ 3 , 4 ] ]
```
returns `[1, 2, 3, 4]` in MATLAB, but it should _really_ return `[1, 2; 3, 4]` which looks like this of course:
```
[1, 2;
 3, 4]
```
Otherwise, there is no way to pass in any 2D array data or column vectors.

**Comment by gaetawoo** [comment]
also, I know that `;` is not a valid TOML character in the numeric sense (which of course it is in MATLAB) which is why the above is needed to pass the same type of information in.

**Comment by gaetawoo** [comment]
I have made a surprisingly simple fix (after a 2 nights of very challenging work that I ended up giving up on) that correctly dimensions multidimensional arrays.  Turning the below input to the below output:

**Input:**
```
a1r2c = [1, 2]
a4d = [[[[1]], [[2]]],[[[4]], [[3]]], [[[6]], [[7]]], [[[8]], [[9]]]]
a1r4csplit = [
	4, 5, 6, 7
]
a3r3csplit = [
	[
		5 , 6 , 8
	], 
	[
		1, 2, 3
	],
	[
		10, 12, 14
	]     
			   
]
a3d = [[[1,1,1],[1,1,1],[1,1,1]],[[2,2,2],[2,2,2],[2,2,2]],[[3,3,3],[3,3,3],[3,3,3]]]
```
**Previous Output:**
```
a = 
  struct with fields:

         a1r2c: [1 2]
           a4d: [1 2 4 3 6 7 8 9]
    a1r4csplit: [4 5 6 7]
    a3r3csplit: [5 6 8 1 2 3 10 12 14]
           a3d: [1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3]
```


**New Output:**
```
a = 
  struct with fields:

         a1r2c: [1 2]
           a4d: [1×1×2×4 double]
    a1r4csplit: [4 5 6 7]
    a3r3csplit: [3×3 double]
           a3d: [3×3×3 double]
```

**Comment by gaetawoo** [comment]
It occurs to me that TOML didn't have multidimensional numeric arrays in mind... that really what I've done is enable a MATLAB structure to be made from TOML. So... yea it'll work in MATLAB but no where else. It also doesn't encode in the same way currently... it's all flat. 

The multidimensional array format is the innermost brackets are a single row with columns separated by commas. Then those brackets are separated by commas to make the rows, then those groups of brackets are separated by commas to make the 3rd dimension, and on and on.  I _think_ this is now numpy works for 3d and beyond.... (tangent: the way you address the dimensions in MATALB and numpy is completely different however, but the layout is as I described I believe).

**Comment by miccoli** [comment]
It is not clear how TOML v0.5.0 valid arrays should be mapped to MATLAB data types. In fact in TOML we have nested arrays, not multidimensional arrays.

Let me express this with an example:

```
arr1 = [[1, 2, 3], ["a", "b", "c"], [1, 2]]
arr2 = [[1, 2], [1, 2, 3]]
arr3 = [[1, 2], [3,4]]
```

While there is no doubt that 

- `arr1` should be a `1x3 cell array` (and matlab-toml correctly decodes this array), 
- `arr2` should be a `1x2 cell array` (matlab-toml fails decoding this ragged array, since current behaviour is to simply concatenate nested numeric arrays)

`arr3` is ambiguous: should it be decoded as
```
arr3 =

  1x2 cell array

    {1x2 double}    {1x2 double}
```
or
```
arr3 =

     1     2
     3     4
```
as @gaetawoo  is proposing?

I have no clear opinion, but maybe a sensible approach would be to map TOML nested arrays into nested 1-dimensional cell arrays. If possible (and may be optionally) the nested structures could be transformed into higher dimensional arrays, but the semantics have to be carefully defined.

Bottom line: TOML data structures do not map well and unambiguously into MATLAB data structures.


Strangely, the other way around, `toml.encode` works as expected:

```
>> s = struct('arr', {{{[1,2], [1,2,3]}, {[1,2]}}})

s = 

  struct with fields:

    arr: {{1x2 cell}  {1x1 cell}}

>> toml.encode(s)                                  

ans =

    'arr = [[[1, 2], [1, 2, 3]], [[1, 2]]]
     '

>> toml.decode(toml.encode(s))

ans = 

  struct with fields:

    arr: [1 2 1 2 3 1 2]

```
but the round trip is not working, as expected.

Another example:

```
>> s = struct('arr', {{{[1,2], [1,2,3]}, [1,2]}})  

s = 

  struct with fields:

    arr: {{1x2 cell}  [1 2]}

>> toml.encode(s)                                

ans =

    'arr = [[[1, 2], [1, 2, 3]], [1, 2]]
     '

>> toml.decode(toml.encode(s))                   

ans = 

  struct with fields:

    arr: [1 2 1 2 3 1 2]

```

**Comment by g-s-k** [comment]
Planning to remove the call to `cell2mat` per analysis above. Thanks for the detailed thoughts.
